---
title: "Homework#3 Problem-4"
output: pdf_document
author: "Arinjay Jain"
---

```{r, include=FALSE}
## Data Load

library ("lars") # For least - angle and lasso
library ("MASS") # For ridge
library ("pls") # For PLS and PCR
library("reshape") # for melt
library(ggplot2)

library ("kernlab")
data("spam")

spam_df <- spam

# changing categorical target variable to numaric 

spam_df$type <- ifelse(spam_df$type=="spam",1,0)

```

```{r, include= TRUE}
mod.ls <- lm(type ~ .-1, spam_df)
mod.ridge <- lm.ridge(type ~ ., spam_df)
mod.pcr <- pcr(formula =type ~ ., data = spam_df, validation ="CV")
mod.plsr <- plsr(formula =type ~ ., data = spam_df, validation ="CV")

mod.lasso <- lars( as.matrix(spam_df[,1:ncol(spam_df) - 1]) ,
spam_df[, ncol(spam_df)],type ="lasso")

mods.coeffs <- data.frame(ls = mod.ls$coef,
ridge = mod.ridge$coef,
lasso = mod.lasso$beta[10 ,],
pcr = mod.pcr$coef[ , ,10],
plsr = mod.plsr$coef [ , ,10]
)
print(mods.coeffs)
mods.coeffs$xs = row.names(mods.coeffs)
plot.data <- melt(mods.coeffs, id ="xs")



ggplot (data = plot.data,
aes (x = factor(xs),y= value,group = variable,
colour = variable)) +
geom_line() +
geom_point() +
xlab("Factor") +
ylab("Regression Coefficient") +
scale_colour_hue(name ="Regression Method ",
labels = c("OLS",
"Ridge",
"Lasso",
"PCR",
"PLS")
)
```

